# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
    
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: rm -rf node_modules/ &&  npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: 
          name: Run Tests
          command: npm test

  deploy:
    machine: true
    

    steps:
      - checkout
        # Deploy Docker 
      - run:
          name: Login Docker
          command: docker login -u$DOCKER_USER -p$DOCKER_PASS

      - run:
          name: Build Docker image
          command: docker build -t kriola/fashionograf-web-ui:$(echo $CIRCLE_SHA1 | cut -c1-7) .      

      -  run:
          name: Push to DockerHub
          command: |
            docker push kriola/fashionograf-web-ui:$(echo $CIRCLE_SHA1 | cut -c1-7)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
          
      