apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fashionograf-ingress-test
spec:
  rules:
  - host: fashionograf.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fashionograf-web-ui-svc
          servicePort: 80