apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fashionograf-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.allow-http: "false"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "1M"
spec:
  rules:
    - host: www.fashionograf.com
      http:
        paths:
          - path: /graphql
            backend:
              serviceName: fashionograf-api-gateway-svc
              servicePort: 80
          - path: /
            backend:
              serviceName: fashionograf-web-ui-svc
              servicePort: 80
  tls:
    - hosts:
        - www.fashionograf.com
      secretName: fashionograf-crt
